version: '3.7'

services:
    nginx:
        container_name: nginx
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "8080-8088:80-88"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./projects/consumers/humanzepola3000_service/humanzepola_backend:/var/www/html/humanzepola3000_service:z
            - ./projects/producers/maternity_hospital_service/maternity_hospital_backend/:/var/www/html/maternity_hospital_service:z
        depends_on:
            - php_maternity_hospital
            - php_humanzepola
        networks:
            - project

    php_maternity_hospital:
        container_name: php_maternity_hospital
        build:
            context: .
            dockerfile: docker/php/maternity_hospital/Dockerfile
        volumes:
            - ./docker/php/maternity_hospital/php.ini:/usr/local/etc/php/php.ini
            - ./projects/producers/maternity_hospital_service/maternity_hospital_backend/:/var/www/html/maternity_hospital_service:z
        depends_on:
            mysql_maternity_hospital:
                condition: service_healthy
#            rabbitmq:
#                condition: service_healthy
        networks:
            - project

    mysql_maternity_hospital:
        container_name: mysql_maternity_hospital
        image: 'mysql/mysql-server:8.0'
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: 'root'
        volumes:
            - 'mysql_maternity_hospital:/var/lib/mysql'
            - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
        networks:
            - project
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-proot'
            retries: 3
            timeout: 5s

    php_humanzepola:
        container_name: php_humanzepola
        build:
            context: .
            dockerfile: docker/php/humanzepola/Dockerfile
        volumes:
            - ./docker/php/humanzepola/php.ini:/usr/local/etc/php/php.ini
            - ./projects/consumers/humanzepola3000_service/humanzepola_backend:/var/www/html/humanzepola3000_service:z
        depends_on:
            mysql_humanzepola:
                condition: service_healthy
#            rabbitmq:
#                condition: service_healthy
        networks:
            - project

    mysql_humanzepola:
        container_name: mysql_humanzepola
        image: 'mysql/mysql-server:8.0'
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: 'root'
        volumes:
            - 'mysql_humanzepola:/var/lib/mysql'
            - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
        networks:
            - project
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-proot'
            retries: 3
            timeout: 5s

    #https://stackoverflow.com/questions/31746182/docker-compose-wait-for-container-x-before-starting-y
#    rabbitmq:
#        container_name: rabbitmq
#        build:
#            context: .
#            dockerfile: docker/rabbitmq/Dockerfile
#        ports:
#            - "15672:15672"
#            - "5672:5672"
#        healthcheck:
#            test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
#            interval: 30s
#            timeout: 10s
#            retries: 5
#        volumes:
#            - rabbitmq-data:/var/lib/rabbitmq
#        networks:
#            - project

networks:
    project:
        driver: bridge

volumes:
#    rabbitmq-data:
    mysql_maternity_hospital:
        driver: local
    mysql_humanzepola:
        driver: local